# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CheckSsl < Formula
  desc "Simple command line utility to check the status of an SSL certificate"
  homepage "https://github.com/colinodell/go-check-ssl"
  version "0.3.0"
  license "MIT"

  on_macos do
    url "https://github.com/colinodell/go-check-ssl/releases/download/v0.3.0/check-ssl_darwin_all.tar.gz"
    sha256 "3cbf5fc62b3334d8c18d013aea8c1ed8c1c4664aa7f78c8cf3b33d3988db74b0"

    def install
      bin.install "check-ssl"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/colinodell/go-check-ssl/releases/download/v0.3.0/check-ssl_linux_amd64.tar.gz"
      sha256 "4b9879f67a5010ef2080b0e38d37e3031e2051dc585574d23c2c3d3bdc0b909d"

      def install
        bin.install "check-ssl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/colinodell/go-check-ssl/releases/download/v0.3.0/check-ssl_linux_arm64.tar.gz"
      sha256 "f0db7bf701ced1ba5a0a4815e4b9c93a5de47e99fa2b01d27e606d23af33e0e9"

      def install
        bin.install "check-ssl"
      end
    end
  end

  test do
    system "#{bin}/check-ssl --version"
  end
end
